/* DFL Golf - Golf Profile + personal club distances. */
import { db } from "./supabase.js";
import { currentMember } from "./members.js";
import { esc, toast } from "./ui.js";
const STARTER=["Driver","3 wood","5 wood","4 hybrid","5 iron","6 iron","7 iron","8 iron","9 iron","Pitching wedge","Gap wedge","Sand wedge","Lob wedge"],SAVE_DELAY=600,timers=new Map();let host=null,profileSeed="handicap";
async function loadMine(id){const{data,error}=await db().from("golf_bag").select("*").eq("member_id",id).order("sort_order").order("id");if(error)throw error;return data||[]}
async function loadVisibility(id){const{data,error}=await db().from("golf_bag_visibility").select("is_public").eq("member_id",id).maybeSingle();if(error)throw error;return!!data?.is_public}
async function loadProfile(id){const{data,error}=await db().from("golf_profiles").select("*").eq("member_id",id).maybeSingle();if(error)throw error;return data||null}
async function loadPublic(id){const[{data:bags,error:be},{data:members,error:me}]=await Promise.all([db().from("golf_bag").select("member_id,club,yards,sort_order,id").neq("member_id",id).order("member_id").order("sort_order"),db().from("members").select("id,display_name,team_name").eq("active",true)]);if(be)throw be;if(me)throw me;const names=new Map((members||[]).map(m=>[String(m.id),m.display_name||m.team_name||`Member ${m.id}`])),groups=new Map();for(const r of bags||[]){const k=String(r.member_id);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r)}return[...groups].map(([id,rows])=>({id,name:names.get(id)||"DFL member",rows}))}
function golfProfile(p){return `<details class="card bag-card"><summary class="card-title-row"><span class="card-title">Handicap & averages</span>${p?.handicap_index!=null?`<span class="pill">HCP ${Number(p.handicap_index).toFixed(1)}</span>`:p?.rating?`<span class="pill">DFL ${Number(p.rating).toFixed(1)}</span>`:""}</summary><form id="golf-profile-form" autocomplete="off"><div class="row" style="gap:8px;align-items:end;flex-wrap:wrap"><label style="flex:1;min-width:90px">Handicap<input id="golf-handicap" data-profile-seed="handicap" type="number" inputmode="decimal" step="0.1" min="-10" max="54" value="${p?.handicap_index??""}" placeholder="14.2"></label><label style="flex:1;min-width:90px">Avg 9<input id="golf-avg9" data-profile-seed="avg9" type="number" inputmode="decimal" step="0.1" min="20" max="100" value="${p?.avg_9??""}" placeholder="45.6"></label><label style="flex:1;min-width:90px">Avg 18<input id="golf-avg18" data-profile-seed="avg18" type="number" inputmode="decimal" step="0.1" min="40" max="200" value="${p?.avg_18??""}" placeholder="91.4"></label></div><div class="row-end"><button class="btn ghost small" type="button" id="golf-profile-autofill">Auto-fill</button><button class="btn small" type="submit">Save</button></div></form></details>`}
function profileError(err){return `<details class="card note"><summary class="card-title">Handicap & averages</summary><div class="card-body muted tiny">Could not load.<br>${esc(err?.message||String(err||"Unknown profile error"))}</div></details>`}
function ownView(rows,me,isPublic){const sorted=[...rows].sort((a,b)=>(b.yards??-1)-(a.yards??-1));return `<details class="card bag-card"><summary class="card-title-row"><span class="card-title">My Golf Bag</span><span class="bag-count">${rows.length}</span></summary><label class="checkrow"><input type="checkbox" id="bag-public" ${isPublic?"checked":""}> <span><strong>Share my bag</strong></span></label>${rows.length?`<div class="bag-list">${sorted.map(r=>`<div class="bag-row" data-row="${r.id}"><input class="bag-club" type="text" value="${esc(r.club)}" maxlength="40" data-field="club"><span class="bag-yards"><input type="text" inputmode="numeric" pattern="[0-9]*" maxlength="3" value="${r.yards??""}" placeholder="—" data-field="yards"><small>yds</small></span><button class="btn ghost small bag-del" data-del="${r.id}">&times;</button></div>`).join("")}</div><div class="arena-admin"><button class="btn ghost small" id="bag-add">Add a club</button></div>`:`<div class="arena-admin"><button class="btn small" id="bag-starter">Start with a full bag</button><button class="btn ghost small" id="bag-add">Add one club</button></div>`}</details>`}
function bagError(err){return `<details class="card note"><summary class="card-title">My Golf Bag</summary><div class="card-body muted tiny">Could not load.<br>${esc(err?.message||String(err||"Unknown bag error"))}</div></details>`}
function publicView(groups){if(!groups.length)return"";return `<details class="card bag-card"><summary class="card-title">Shared DFL Bags</summary>${groups.map(g=>`<details class="card bag-card"><summary class="card-title">${esc(g.name)}'s bag <span class="bag-count">${g.rows.length}</span></summary><div class="bag-list">${[...g.rows].sort((a,b)=>(b.yards??-1)-(a.yards??-1)).map(r=>`<div class="bag-row"><strong class="bag-club">${esc(r.club)}</strong><span class="bag-yards"><b>${r.yards??"—"}</b><small>yds</small></span></div>`).join("")}</div></details>`).join("")}</details>`}
function publicError(err){if(err)console.warn("golf bag: shared bags unavailable",err);return""}
async function draw(){const me=currentMember();if(!host)return;if(!me){host.innerHTML="";return}const[mineRes,visRes,profileRes,publicRes]=await Promise.allSettled([loadMine(me.id),loadVisibility(me.id),loadProfile(me.id),loadPublic(me.id)]);if(!host)return;const rows=mineRes.status==="fulfilled"?mineRes.value:[],isPublic=visRes.status==="fulfilled"?visRes.value:false;let html=`<section class="block golf-personal-tools"><h2 class="section-title">My Golf</h2>`;html+=profileRes.status==="fulfilled"?golfProfile(profileRes.value):profileError(profileRes.reason);html+=mineRes.status==="fulfilled"?ownView(rows,me,isPublic):bagError(mineRes.reason);if(publicRes.status==="fulfilled")html+=publicView(publicRes.value);else html+=publicError(publicRes.reason);html+=`</section>`;host.innerHTML=html}
function queue(id,field,getValue){const k=`${id}:${field}`;clearTimeout(timers.get(k));timers.set(k,setTimeout(async()=>{timers.delete(k);const raw=getValue(),patch=field==="yards"?{yards:raw===""?null:Math.max(1,Math.min(999,Number(raw)))}:{club:raw.trim()||"Club"};try{const{error}=await db().from("golf_bag").update({...patch,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error}catch(err){toast(err.message||"Could not save that",true);draw()}},SAVE_DELAY))}
const round1=n=>Math.round(Number(n)*10)/10;
function estimateHandicap(avg18){return Math.max(-10,Math.min(54,round1(Number(avg18)-72)))}
function autoFillProfile(){const h=host.querySelector("#golf-handicap"),a9=host.querySelector("#golf-avg9"),a18=host.querySelector("#golf-avg18"),value=el=>el?.value===""?null:Number(el.value);let seed=profileSeed,src=seed==="handicap"?value(h):seed==="avg9"?value(a9):value(a18);if(src==null||!Number.isFinite(src)){for(const candidate of ["handicap","avg18","avg9"]){const v=candidate==="handicap"?value(h):candidate==="avg18"?value(a18):value(a9);if(v!=null&&Number.isFinite(v)){seed=candidate;src=v;break}}}if(src==null||!Number.isFinite(src)){toast("Enter a handicap, Avg 9, or Avg 18 first",true);return}let handicap,nine,eighteen;if(seed==="handicap"){handicap=Math.max(-10,Math.min(54,round1(src)));eighteen=round1(72+handicap);nine=round1(eighteen/2)}else if(seed==="avg18"){eighteen=round1(src);nine=round1(eighteen/2);handicap=estimateHandicap(eighteen)}else{nine=round1(src);eighteen=round1(nine*2);handicap=estimateHandicap(eighteen)}h.value=handicap;a9.value=nine;a18.value=eighteen;profileSeed=seed;toast(`Auto-filled from ${seed==="handicap"?"handicap":seed==="avg9"?"Avg 9":"Avg 18"}`)}
function wire(){host.addEventListener("submit",async e=>{if(e.target.id!=="golf-profile-form")return;e.preventDefault();const val=id=>{const s=host.querySelector(id)?.value?.trim();return s===""?null:Number(s)},btn=e.target.querySelector('button[type="submit"]');btn.disabled=true;try{const{error}=await db().rpc("golf_save_profile_and_reprice",{new_handicap:val("#golf-handicap"),new_avg_9:val("#golf-avg9"),new_avg_18:val("#golf-avg18")});if(error)throw error;toast("Golf Profile saved · Sportsbook repriced");draw()}catch(err){toast(err.message||"Could not save Golf Profile",true);btn.disabled=false}});host.addEventListener("input",e=>{const seed=e.target.closest("[data-profile-seed]");if(seed){profileSeed=seed.dataset.profileSeed;return}const input=e.target.closest("[data-field]");if(!input)return;if(input.dataset.field==="yards"){const clean=input.value.replace(/\D/g,"").slice(0,3);if(clean!==input.value)input.value=clean}const id=input.closest("[data-row]")?.dataset.row;if(id)queue(id,input.dataset.field,()=>input.value)});host.addEventListener("change",async e=>{const t=e.target.closest("#bag-public");if(!t)return;const me=currentMember();if(!me)return;t.disabled=true;try{const{error}=await db().from("golf_bag_visibility").upsert({member_id:me.id,is_public:t.checked,updated_at:new Date().toISOString()},{onConflict:"member_id"});if(error)throw error;toast(t.checked?"Your bag is now public":"Your bag is private again");draw()}catch(err){toast(err.message||"Could not change bag visibility",true);t.disabled=false}});host.addEventListener("click",async e=>{const auto=e.target.closest("#golf-profile-autofill");if(auto){autoFillProfile();return}const del=e.target.closest("[data-del]"),add=e.target.closest("#bag-add"),starter=e.target.closest("#bag-starter"),me=currentMember();if(!me)return;if(del){const row=del.closest("[data-row]"),name=row?.querySelector(".bag-club")?.value||"that club";if(!confirm(`Remove ${name} from your bag?`))return;try{const{error}=await db().from("golf_bag").delete().eq("id",del.dataset.del);if(error)throw error;draw()}catch(err){toast(err.message||"Could not remove that club",true)}return}if(add||starter){const clubs=starter?STARTER:["New club"];e.target.disabled=true;try{const{error}=await db().from("golf_bag").insert(clubs.map((club,i)=>({member_id:me.id,club,sort_order:i})));if(error)throw error;draw()}catch(err){toast(err.message||"Could not add that",true);e.target.disabled=false}}})}
function boot(){const find=()=>{const el=document.querySelector("#golf-wrap .golf-bag-page");if(!el||el===host)return;host=el;const wrap=el.closest("#golf-wrap");const history=[...(wrap?.querySelectorAll(".section-title")||[])].find(h=>h.textContent.trim().startsWith("Golf history"));if(history&&el.nextElementSibling!==history)wrap.insertBefore(el,history);wire();draw()};new MutationObserver(find).observe(document.body,{childList:true,subtree:true});find()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();